version: '3.1'

services:
  reverseproxy:
    image: 'reverseproxy'
    build: './proxy'
    ports:
      - 80:80
    restart: always

  test:
    image: 'test'
    build: '.'
    ports:
      - 3000:80
    depends_on:
      - reverseproxy
    restart: always
